name: CI Portfolio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Verificación de Tipos (TypeScript)
        run: npx tsc --noEmit

      - name: Verificación de Linter (ESLint)
        run: npm run lint

      - name: Prueba de Build (Next.js)
        run: npm run build
